### ISSUE TITLE
Make the smoke interactive

### ISSUE THREAD

**Issue by lukaskollmer** [arkis/arkis.io#5]
I don't know if this is possible, but it'd be cool if the smoke could react to the cursor in some way. Like that when you move the cursor, you can push it away or something like that

**Comment by controversial** [comment]
That would be really cool. Don't think it's practical given that the particles are actually very large and textured, they're not as fine as they seem. So I don't think the effect could be very good for now, and using more, smaller, particles would be more computationally intensive. This is a cool idea, but I'm going to close it for now
