### ISSUE TITLE
Make buttons great again.

### ISSUE THREAD

**Issue by EightBitBoot** [arkis/arkis.io#7]
The twitter buttons should be the whole card instead of only the handles.

**Comment by JosephBywater** [comment]
I thought that too, but maybe @controversial wants more social links on each card and it wouldn't make sense?

**Comment by controversial** [comment]
Actually I changed my mind on this one, I don't think the "main focus" of the cards should be twitter, that's just a detail. I'd like to keep the links small. I'm also gonna add GitHub and maybe even Instagram links. So yeah, I changed my mind
