### ISSUE TITLE
Mobile navbar menu

### ISSUE THREAD

**Issue by JosephBywater** [arkis/arkis.io#9]
When the navbar changed to fit the white section the hamburger menu has the same styling as on the dark area.

**Comment by JosephBywater** [comment]
https://imgur.com/gallery/QyuUB

**Comment by controversial** [comment]
What's the issue?

**Comment by JosephBywater** [comment]
It doesn't fit the white navbar's look. ¯\_(ツ)_/¯

**Comment by controversial** [comment]
That's a conscious decision. It looks as intended
